version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: tpv-mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpv_auth
      MYSQL_USER: tpv_user
      MYSQL_PASSWORD: tpv_pass

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
